plugin:
  name: custom-data-type-dante
  version: 1.2
  url: https://github.com/programmfabrik/easydb-custom-data-type-dante
  displayname:
    de-DE: DANTE-Verknüpfung
    en-US: DANTE-Referencing
  info:
    de-DE: Stellt Verknüpfungen mit dem Normdatenserver DANTE her.
    en-US: Use for references to entities of DANTE-AuthorityFile-Server.
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-dante.js
    l10n: l10n/
    css: custom-data-type-dante.css
custom_types:
  dante:
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
    config:
      schema:
        - name: vocabulary_name
          parameters:
            value:
              type: text
        - name: mapbox_access_token
          parameters:
            value:
              type: text
      mask:
        - name: editor_style
          parameters:
            value:
              type: select
              options: ["dropdown", "popover", "popover_with_treeview"]
        - name: use_cache
          parameters:
            value:
              type: bool
        - name: allow_label_choice
          parameters:
            value:
              type: bool
        - name: default_concept_uuid
          parameters:
            value:
              type: text
        - name: default_concept_name
          parameters:
            value:
              type: text