plugin:
  name: custom-data-type-dante
  version: 1.3
  url: https://github.com/programmfabrik/easydb-custom-data-type-dante
  displayname:
    de-DE: DANTE-Verknüpfung
    en-US: DANTE-Referencing
  info:
    de-DE: Stellt Verknüpfungen mit dem Normdatenserver DANTE her.
    en-US: Use for references to entities of DANTE-AuthorityFile-Server.
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-dante.js
    l10n: l10n/
    css: custom-data-type-dante.css
custom_types:
  dante:
    update:
      script: build/updater/dante-update.js
      timeout: 60
      batch_size: 100
      interval_base_config: update_interval_dante.days
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
      conceptAncestors:
        type: text
    config:
      schema:
        - name: vocabulary_name
          parameters:
            value:
              type: text
        - name: mapbox_access_token
          parameters:
            value:
              type: text
      mask:
        - name: editor_style
          parameters:
            value:
              type: select
              options: ["popover", "popover_with_treeview", "dropdown"]
        - name: use_cache
          parameters:
            value:
              type: bool
        - name: allow_label_choice
          parameters:
            value:
              type: bool
        - name: default_concept_uri
          parameters:
            value:
              type: text
        - name: default_concept_name
          parameters:
            value:
              type: text
base_config:
  - name: update_interval_dante
    group: update_custom_data_type
    parameters:
      days:
        type: int
        min: 0
        default: 0
        position: 0
      default_language:
        type: text
        default: 'de'
        position: 1
